@HranitelProAPi_HostAddress = http://127.0.0.1:5203

GET {{HranitelProAPi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HranitelProAPi_HostAddress}}/api/health/ping
Accept: application/json

###
